import {
  BoxIcon,
  BrainCog,
  Calendar,
  Check,
  Facebook,
  GlobeIcon,
  HelpCircleIcon,
  LanguagesIcon,
  LayoutList,
  ListChecks,
  ListOrderedIcon,
  Mail,
  Mic2,
  Mic2Icon,
  PartyPopper,
  PenTool,
  SignalHigh,
  SignalLow,
  Speaker,
  Twitter,
  WandIcon,
} from "lucide-react";

export const Icons = {
  BrainCog: <BrainCog />,
  PenTool: <PenTool />,
  LayoutList: <LayoutList />,
  Facebook: <Facebook />,
  Twitter: <Twitter />,
  PartyPopper: <PartyPopper />,
  ListChecks: <ListChecks />,
  Calendar: <Calendar />,
  Mail: <Mail />,
  Check: <Check />,
  SignalLow: <SignalLow />,
  SignalHigh: <SignalHigh />,
  Mic2: <Mic2Icon />,
  Wand: <WandIcon />,
  Box: <BoxIcon />,
  Languages: <LanguagesIcon />,
  HelpCircle: <HelpCircleIcon />,
  ListOrdered: <ListOrderedIcon />,
};
